version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_data
    ports:
      - "5432:5432"
    volumes:
        - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: