version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:8.10.2
    container_name: logstash
    volumes:
      - ./logstash/:/logstash_dir
      - /Users/glebsoldatenko/Desktop/java_idea/fintech/task1/logs/:/logs
    command: logstash -f /logstash_dir/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      - "LOGSTASH_MONITORING=true"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  pg_data:
  es_data:
  elastic_data: