name: Build on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Build project with gradle
      - name: Build hw5 with Gradle
        run: ./gradlew clean build -PtestPackage --no-daemon

      - name: Run tests with code coverage
        run: ./gradlew test --tests "org.tbank.hw5.*" jacocoTestReport
      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: build/reports/jacoco/test/html/

      # Run Checkstyle
      - name: Run Checkstyle Analysis
        run: ./gradlew checkstyleMain checkstyleTest

      # Upload Checkstyle report as artifact
      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/

      # Convert repository name to lowercase
      - name: Convert repository name to lowercase
        id: lowercase_repo
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.REPO_NAME }}/my-docker-image:${{ github.sha }} .

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/my-docker-image:${{ github.sha }}